Update 20210611_1

diff --git a/Linux/20210611/20210611_1 b/Linux/20210611/20210611_1
--- a/Linux/20210611/20210611_1
+++ b/Linux/20210611/20210611_1
@@ -1,1 +1,17 @@
 
+#!/bin/bash
+PREFIX=194.145.63
+for OCTET in `seq 1 255`
+do
+	echo -en "Pinging ${PREFIX}.${OCTET}...."
+	ping -c1 -w1 ${PREFIX}.${OCTET} > /dev/null 2>&1
+	if [ "$?" -eq "0" ];
+	then
+		echo "OK"
+		echo "${PREFIX}.${OCTET} OK `date`" >> test_ping.sh
+		
+	else
+		echo "FAILED"
+		echo "${PREFIX}.${OCTET} FAILED `date`" >> test_ping.sh
+	fi
+done
